from __future__ import annotations

from dataclasses import dataclass
from io import StringIO
from typing import Callable

import pandas as pd
import requests


@dataclass(frozen=True)
class UniverseSpec:
    name: str
    source_url: str
    suffix: str = ""
    dot_to_dash: bool = False
    parser: Callable[[list[pd.DataFrame], "UniverseSpec"], pd.DataFrame] | None = None
    benchmark_ticker: str = ""


def _clean_columns(frame: pd.DataFrame) -> pd.DataFrame:
    result = frame.copy()
    result.columns = [
        str(col[-1] if isinstance(col, tuple) else col).strip()
        for col in result.columns
    ]
    return result


def _find_table(tables: list[pd.DataFrame], required_any: tuple[str, ...]) -> pd.DataFrame:
    for raw in tables:
        frame = _clean_columns(raw)
        names = {str(column).lower() for column in frame.columns}
        if all(any(token in name for name in names) for token in required_any):
            return frame
    raise ValueError("Constituent table not found in source page.")


def _pick_column(frame: pd.DataFrame, candidates: tuple[str, ...]) -> str | None:
    for candidate in candidates:
        for column in frame.columns:
            if candidate in str(column).lower():
                return str(column)
    return None


def normalize_ticker(value: object, spec: UniverseSpec) -> str:
    """Convert a source ticker into the Yahoo Finance symbol for the universe."""
    ticker = str(value).strip().upper()

    if not ticker or ticker in {"NAN", "NONE", "<NA>"}:
        return ""

    ticker = ticker.replace(" ", "")

    if spec.suffix:
        suffix = spec.suffix.upper()
        dashed_suffix = suffix.replace(".", "-")

        # Repair malformed symbols generated by older code, e.g. A2A-MI.MI.
        while ticker.endswith(suffix):
            ticker = ticker[: -len(suffix)]
        while dashed_suffix and ticker.endswith(dashed_suffix):
            ticker = ticker[: -len(dashed_suffix)]

        ticker = f"{ticker}{suffix}"
    elif spec.dot_to_dash:
        # Yahoo uses dashes for US share classes: BRK.B -> BRK-B.
        ticker = ticker.replace(".", "-")

    return ticker


def _standardize(frame: pd.DataFrame, spec: UniverseSpec) -> pd.DataFrame:
    company_col = _pick_column(frame, ("company", "constituent", "security", "name"))
    ticker_col = _pick_column(frame, ("ticker", "symbol", "epic"))
    sector_col = _pick_column(frame, ("gics sector", "icb sector", "industry", "sector"))

    if not company_col or not ticker_col:
        raise ValueError("Company/ticker columns not available.")

    result = pd.DataFrame(
        {
            "Company": (
                frame[company_col]
                .astype(str)
                .str.replace(r"\[.*?\]", "", regex=True)
                .str.strip()
            ),
            "Ticker": (
                frame[ticker_col]
                .astype(str)
                .str.replace(r"\[.*?\]", "", regex=True)
                .str.strip()
            ),
            "Sector": (
                frame[sector_col].astype(str).str.strip()
                if sector_col
                else "Unclassified"
            ),
        }
    )

    result["Ticker"] = result["Ticker"].map(lambda value: normalize_ticker(value, spec))

    return (
        result.replace({"nan": pd.NA, "None": pd.NA, "": pd.NA})
        .dropna(subset=["Ticker"])
        .drop_duplicates("Ticker")
        .reset_index(drop=True)
    )


def _parse_sp500(tables: list[pd.DataFrame], spec: UniverseSpec) -> pd.DataFrame:
    return _standardize(_find_table(tables, ("symbol", "security")), spec)


def _parse_nasdaq100(tables: list[pd.DataFrame], spec: UniverseSpec) -> pd.DataFrame:
    return _standardize(_find_table(tables, ("ticker", "company")), spec)


def _parse_ftse_mib(tables: list[pd.DataFrame], spec: UniverseSpec) -> pd.DataFrame:
    return _standardize(_find_table(tables, ("ticker", "company")), spec)


def _parse_dax(tables: list[pd.DataFrame], spec: UniverseSpec) -> pd.DataFrame:
    return _standardize(_find_table(tables, ("ticker", "company")), spec)


UNIVERSES: dict[str, UniverseSpec] = {
    "NASDAQ 100": UniverseSpec(
        name="NASDAQ 100",
        source_url="https://en.wikipedia.org/wiki/Nasdaq-100",
        dot_to_dash=True,
        parser=_parse_nasdaq100,
        benchmark_ticker="^NDX",
    ),
    "S&P 500": UniverseSpec(
        name="S&P 500",
        source_url="https://en.wikipedia.org/wiki/List_of_S%26P_500_companies",
        dot_to_dash=True,
        parser=_parse_sp500,
        benchmark_ticker="^GSPC",
    ),
    "FTSE MIB": UniverseSpec(
        name="FTSE MIB",
        source_url="https://en.wikipedia.org/wiki/FTSE_MIB",
        suffix=".MI",
        parser=_parse_ftse_mib,
        benchmark_ticker="FTSEMIB.MI",
    ),
    "DAX 40": UniverseSpec(
        name="DAX 40",
        source_url="https://en.wikipedia.org/wiki/DAX",
        suffix=".DE",
        parser=_parse_dax,
        benchmark_ticker="^GDAXI",
    ),
}


_FALLBACKS: dict[str, list[tuple[str, str, str]]] = {
    "FTSE MIB": [
        ("A2A", "A2A.MI", "Utilities"), ("Amplifon", "AMP.MI", "Health Care"),
        ("Azimut", "AZM.MI", "Financials"), ("Banca Mediolanum", "BMED.MI", "Financials"),
        ("Banca Monte dei Paschi", "BMPS.MI", "Financials"), ("Banco BPM", "BAMI.MI", "Financials"),
        ("BPER Banca", "BPE.MI", "Financials"), ("Brunello Cucinelli", "BC.MI", "Consumer Discretionary"),
        ("Campari", "CPR.MI", "Consumer Staples"), ("DiaSorin", "DIA.MI", "Health Care"),
        ("Enel", "ENEL.MI", "Utilities"), ("Eni", "ENI.MI", "Energy"),
        ("Ferrari", "RACE.MI", "Consumer Discretionary"), ("FinecoBank", "FBK.MI", "Financials"),
        ("Generali", "G.MI", "Financials"), ("Hera", "HER.MI", "Utilities"),
        ("InPost", "INPST.AS", "Industrials"), ("Intesa Sanpaolo", "ISP.MI", "Financials"),
        ("Italgas", "IG.MI", "Utilities"), ("Leonardo", "LDO.MI", "Industrials"),
        ("Lottomatica", "LTMC.MI", "Consumer Discretionary"), ("Mediobanca", "MB.MI", "Financials"),
        ("Moncler", "MONC.MI", "Consumer Discretionary"), ("Nexi", "NEXI.MI", "Information Technology"),
        ("Pirelli", "PIRC.MI", "Consumer Discretionary"), ("Poste Italiane", "PST.MI", "Financials"),
        ("Prysmian", "PRY.MI", "Industrials"), ("Recordati", "REC.MI", "Health Care"),
        ("Saipem", "SPM.MI", "Energy"), ("Snam", "SRG.MI", "Utilities"),
        ("Stellantis", "STLAM.MI", "Consumer Discretionary"), ("STMicroelectronics", "STM.MI", "Information Technology"),
        ("Telecom Italia", "TIT.MI", "Communication Services"), ("Tenaris", "TEN.MI", "Energy"),
        ("Terna", "TRN.MI", "Utilities"), ("UniCredit", "UCG.MI", "Financials"),
        ("Unipol", "UNI.MI", "Financials"), ("Interpump", "IP.MI", "Industrials"),
        ("Iveco", "IVG.MI", "Industrials"), ("Buzzi", "BZU.MI", "Materials"),
    ],
    "NASDAQ 100": [
        ("Apple", "AAPL", "Technology"), ("Microsoft", "MSFT", "Technology"),
        ("NVIDIA", "NVDA", "Technology"), ("Amazon", "AMZN", "Consumer Discretionary"),
        ("Alphabet A", "GOOGL", "Communication Services"), ("Alphabet C", "GOOG", "Communication Services"),
        ("Meta Platforms", "META", "Communication Services"), ("Broadcom", "AVGO", "Technology"),
        ("Tesla", "TSLA", "Consumer Discretionary"), ("Costco", "COST", "Consumer Staples"),
        ("Netflix", "NFLX", "Communication Services"), ("AMD", "AMD", "Technology"),
        ("Adobe", "ADBE", "Technology"), ("PepsiCo", "PEP", "Consumer Staples"),
        ("Cisco", "CSCO", "Technology"), ("T-Mobile US", "TMUS", "Communication Services"),
        ("Intuit", "INTU", "Technology"), ("Qualcomm", "QCOM", "Technology"),
        ("Amgen", "AMGN", "Health Care"), ("Applied Materials", "AMAT", "Technology"),
        ("Booking Holdings", "BKNG", "Consumer Discretionary"), ("Micron", "MU", "Technology"),
        ("Palo Alto Networks", "PANW", "Technology"), ("Intel", "INTC", "Technology"),
        ("Comcast", "CMCSA", "Communication Services"), ("Starbucks", "SBUX", "Consumer Discretionary"),
        ("Gilead", "GILD", "Health Care"), ("MercadoLibre", "MELI", "Consumer Discretionary"),
        ("Honeywell", "HON", "Industrials"), ("Vertex", "VRTX", "Health Care"),
    ],
}


def fallback_universe(name: str) -> pd.DataFrame:
    records = _FALLBACKS.get(name)
    if not records:
        return pd.DataFrame(columns=["Company", "Ticker", "Sector"])

    frame = pd.DataFrame(records, columns=["Company", "Ticker", "Sector"])
    spec = UNIVERSES[name]
    frame["Ticker"] = frame["Ticker"].map(lambda value: normalize_ticker(value, spec))
    return frame.drop_duplicates("Ticker").reset_index(drop=True)


def load_universe(name: str, timeout: int = 15) -> tuple[pd.DataFrame, str]:
    if name not in UNIVERSES:
        raise KeyError(f"Unknown universe: {name}")

    spec = UNIVERSES[name]
    if spec.parser is None:
        raise ValueError(f"Parser not configured for universe: {name}")

    try:
        response = requests.get(
            spec.source_url,
            timeout=timeout,
            headers={"User-Agent": "Cyclical-Terminal/1.0"},
        )
        response.raise_for_status()
        tables = pd.read_html(StringIO(response.text))
        frame = spec.parser(tables, spec)
        if len(frame) < 20:
            raise ValueError("Constituent table unexpectedly small.")
        return frame, spec.source_url
    except Exception:
        fallback = fallback_universe(name)
        if fallback.empty:
            raise
        return fallback, "bundled fallback snapshot"
